apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
  namespace: produzione-wqlmd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      # Secret per GitHub
      imagePullSecrets:
      - name: docker-imagepull-secret
      containers:
      - name: nginx
        # Immagine su GHCR
        image: ghcr.io/demoitaly/web-server:v1.0.0
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-lb
  namespace: produzione-wqlmd
spec:
  # Load Balancer nativo di NKP
  type: LoadBalancer
  selector:
    app: web-server
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
