apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: demo
spec:
  image: 10.38.36.43:5000/pcm/html
  interval: 1m0s
  secretRef:
    name: docker-imagepull-secret
  certSecretRef:
    name: harbor-ca
