apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.pathmatcher: PathPrefix
    traefik.ingress.kubernetes.io/router.entrypoints: websecure   
  name: wildfly-ing
  namespace: demo
spec:
  ingressClassName: kommander-traefik
  rules:
    - host: myappa
      http:
        paths:
          - path: /jboss-as-helloworld
            pathType: Prefix
            backend:
              service:
                name: wildfly-svc
                port:
                  number: 8080
